on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: nix build .#default
      - name: Test
        run: nix develop .#default --command cargo test
